### ISSUE TITLE
Make next/previous buttons more visible

### ISSUE THREAD

**Issue by ppawel** [ppawel/openstreetmap-website#1]
From talk@:

```
In the History tab, the arrows at the bottom to go to the next page could be more visual. You could maybe simply add a text like Next page. 
```

**Comment by rnorris** [comment]
I like the arrows!
The image could do with being much bigger.

I don't think putting in text 'Next', is a good idea - since now it needs translating into all the various languages used.

**Comment by ppawel** [comment]
Next/previous text is already used in other parts of the application so the translations are there.

**Comment by ppawel** [comment]
Closing as there is no prev/next buttons anymore.
