### ISSUE TITLE
Changeset/item and geometry highlighting in both directions

### ISSUE THREAD

**Issue by BushmanK** [ppawel/openstreetmap-website#15]
Currently, when you pointing with a cursor on map geometry, list item become highlighted with grey background, so it's easy to find corresponding changeset. 
But it's impossible to find corresponding geometry when browsing the changeset list.
In case of modified geometry, it's possible to hover the "show previous geometry" and see the changing way, but in case of new object or object with modified tag, you can't do it.
So it will be handy, if highlighting will work bidirectionally from map (as it currently does) and from list (for example, by hovering the added "show on map" link).

**Comment by ppawel** [comment]
Thanks for the report. This used to work but after major UI changes got lost in action. I will reimplement it.
