### ISSUE TITLE
new coordinate notation doesn't work

### ISSUE THREAD

**Issue by malenki** [ppawel/openstreetmap-website#24]
After osm.org was overhauled there is a new notation of the coordinates looking like this: http://www.osm.org/#map=13/52.9559/12.9146
Because http://owl.apis.dev.osm.org is not linked from the main site usually I copy a part of the URL from an owl bookmark to the OSM url or vice versa.
Now after osm changing its notation this doesn't work anymore because owl only understands this:
http://owl.apis.dev.openstreetmap.org/?lat=52.9559&lon=12.9146

Enhancing this would be nice (making it live even nicer :) )

**Comment by ppawel** [comment]
Merge of the latest osm-website master is done so this is fixed.
