### ISSUE TITLE
Current status: OWL API OK - HISTORY PROCESSING IN PROGRESS

### ISSUE THREAD

**Issue by grinapo** [ppawel/openstreetmap-website#31]
It does not look like it's true. At least yesterday still not visible, like changeset #19766614...

**Comment by Rovastar** [comment]
Ummh it does seem to have stopped updating.....it seems to have stopped updating towards the end of last year.

**Comment by ppawel** [comment]
Yes, disk space has ran out. I moved some Postgres indexes between disks and now it is updating again, it has some backlog to process though...

**Comment by grinapo** [comment]
Is it full again? Doesn't seem to be updated for 2 weeks now.
