### ISSUE TITLE
history tab has an unusually high lag

### ISSUE THREAD

**Issue by matkoniecz** [ppawel/openstreetmap-website#35]
Nothing appears, in history tab, "keep waiting" symbol is animated but nothing appears even after a long time. Sometimes something appears, but it is necessary to wait a long time and try multiple times.

**Comment by tomchance** [comment]
I've had the same problem recently. Is it broken?

**Comment by ppawel** [comment]
Unfortunately it is because the server is out of disk space on the SSD drive and I had to move some tables (ways) to the HDD (spinning drive) so now it's much slower...

**Comment by tomchance** [comment]
I see! Fair enough... it would be wonderful to have this service on the OSM homepage one day, it's so much more useful than any other interface I've come across.

**Comment by openbrian** [comment]
Food for thought.  The SSD can be configured to be a cache for the HHD.  See http://en.wikipedia.org/wiki/Dm-cache

**Comment by grinapo** [comment]
Or use flashcache.

**Comment by ppawel** [comment]
Closing this, see status update in #36.
