### ISSUE TITLE
Popup often in the way when using "show previous geometry"

### ISSUE THREAD

**Issue by tyrasd** [ppawel/openstreetmap-website#5]
The object details popup always hides content directly next to the object one is interested in. This is especially bad when using the "show previous geometry" tool as the result can be hidden easily by the popup.
The popup also sometimes causes annoying auto-panning of the map, which causes unnecessary reloads of the history and some flickering while reloading the data.

You could use a slightly transparent popup, or (better IMHO) use some other kind of overlay which is not near to the element (e.g. in one of the corners of the map) to show the details.

**Comment by ppawel** [comment]
Thanks for the report. It is indeed very annoying. I like your suggestion about using a separate element to show object details. I will experiment with that solution.

**Comment by tyrasd** [comment]
Hey! I've been experimenting with floating popups in leaflet, today. Now, I have a _prototype_ of a leaflet-plugin, which provides such functionality.

Maybe, you like to try it with your code... Just grab the following and replace `L.popup()` with `L.overlayPopup()` :
https://github.com/tyrasd/overpass-ide/blob/overlay_popups/libs/OverlayPopup.js

**Comment by ppawel** [comment]
@tyrasd Thanks for the hint. It works however I'm still not sure where should this popup be displayed - lower left corner maybe?

I had another idea to use the sidebar to display popup contents - when you click on geometry the sidebar changes from a list to displaying details for one specific changeset + details for one specific change that was clicked.

**Comment by tyrasd** [comment]
Your idea sounds better thought-out. That would also be consistent with the behavior the website already shows when clicking on objects in the "Browse Map Data" mode.

**Comment by ppawel** [comment]
Yeah, I'm just a bit worried that it could make the interface too complicated with too many states and screens. I will do some experiments and see how it turns out.

**Comment by ppawel** [comment]
I pushed a lot of changes - there is no popups anymore. Now I need to work on making the sidebar less crowded...

**Comment by ppawel** [comment]
Closing as there is no popups anymore.
