### ISSUE TITLE
Replace &raquo; with "load more" or infinite scrolling

### ISSUE THREAD

**Issue by systemed** [ppawel/openstreetmap-website#9]
At present the link for “see next page of changes” is a double-chevron (»). This is slightly unintuitive, especially because it suggests "go right" and actually the direction of reading is down.

It would be better if there was either a "load more" button, which appended the next changes to the current page, and/or an "infinite scrolling"-type view, where scrolling beyond the bottom of the current list automatically loads and appends the next lot.

**Comment by ppawel** [comment]
Richard, thanks for the suggestion. Indeed paging or in general - viewing more data - needs to be solved better. There was already a request for "infinite" scroll. Here is a copy of my reply from the mailing list:

> I thought about that but there's one problem - if there is continuous
> scroll then you will get more and more changesets by scrolling down. And
> that means that the user probably expects all of them to be displayed
> and that's problematic because browser performance/responsivness
> decreases very sharply as the number of geometry features grows beyond
> some point. 

I think that this problem also affects a solution with "load more" button. If you have any ideas how to neatly solve this UI-wise let me know :)

**Comment by systemed** [comment]
You could perhaps shift changesets off the top at the same time as pushing them onto the bottom? (as defined by a certain maximum, e.g. 20)

**Comment by ppawel** [comment]
Yeah, that's probably the only feasible solution right now. As an alternative I was thinking about displaying as many changesets on the list as the user wants but only showing geometry for 15-20 of them but that would get complicated - how does the user select those changesets etc...

So for now I will just improve paging as you suggested.

**Comment by ppawel** [comment]
Reopening as I've got an idea how to implement the infinite scrolling and get away with it performance-wise.

**Comment by ppawel** [comment]
Done.

**Comment by systemed** [comment]
_applauds_
